CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(50),
   password VARCHAR(255),
   role VARCHAR(255),
   CONSTRAINT pk_app_user PRIMARY KEY (id)
);

ALTER TABLE app_user ADD CONSTRAINT uc_app_user_username UNIQUE (username);