CREATE TABLE IF NOT EXISTS question (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   question_text VARCHAR(255),
   answer VARCHAR(255),
   CONSTRAINT pk_question PRIMARY KEY (id)
);

ALTER TABLE question ADD CONSTRAINT uc_question_question_text UNIQUE (question_text);